services:
  sampleproject:
    image: saam-frontend:latest
    container_name: saam-frontend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    env_file:
      - .env
    environment:
      NODE_ENV: production
      VITE_API_URL: ${VITE_API_URL}